### ISSUE TITLE
 devx run dev --list-all Error: field not found: builders

### ISSUE THREAD

**Issue by gedw99** [devopzilla/guku-devx#29]
in the simple example i am trying to run taskfile

``` 
simple % devx run dev --list-all
Error: field not found: builders
```

**Comment by kajogo777** [comment]
A few things might be wrong

0) Did you initialize the project? and installed dependencies?
```bash
devx project init
devx project update
```


1) You have to copy the `builders.cue` file in the example as well this defines the builders, this tells devx how to transform the stack
https://docx.guku.io/docs/examples/simple
```cue
package main

import (
    "guku.io/devx/v2alpha1"
    "guku.io/devx/v2alpha1/environments"
)

builders: v2alpha1.#Environments & {
    dev: environments.#Compose
}
```

2) the simple example doesn't define a taskfile, you need a taskfile to be able to run tasks
for example
```cue
package main

import (
    "guku.io/devx/v2alpha1"
    "guku.io/devx/v2alpha1/environments"
)

builders: v2alpha1.#Environments & {
    dev: environments.#Compose & {
        taskfile: who: "whoami"
    }
}
```
```bash
devx run dev who
> george
```

@gedw99  Please let me know which step went wrong, so we can improve error reporting.

**Comment by kajogo777** [comment]
I pushed a quick fix that adds more validation before trying to parse the `builder`, now you should get a more descriptive error if you forgot to init the project
```bash
devx run dev --list-all
Error: import failed: cannot find package "guku.io/devx/v2alpha1"
```
Or if `taskfile` is not defined like in the simple example
```bash
devx run dev --list-all
Error: no taskfile definition found in environment dev
```

https://github.com/devopzilla/guku-devx/releases/tag/v0.3.24

Thanks @gedw99 for reporting this.
